### ISSUE TITLE
Clash between precise64 and Virtualbox additions

### ISSUE THREAD

**Issue by marsbard** [maoo/alfresco-boxes#19]
Getting the error below when trying to run "vagrant up" on precise 64 - this is something I have seen a lot with my own puppet/vagrant projects
 
I've added a new BOX_OS clause for a "trusty64" box which I got from here: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box - if you like I can make a pull request, or if the issue only occurs with me I can keep it for myself 

Installing Virtualbox Guest Additions 4.3.10 - guest version is 4.2.0
stdin: is not a tty
Verifying archive integrity... All good.
Uncompressing VirtualBox 4.3.10 Guest Additions for Linux............
VirtualBox Guest Additions installer
Removing installed version 4.2.0 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox DKMS kernel modules ...done.
Removing existing VirtualBox non-DKMS kernel modules ...done.
Building the VirtualBox Guest Additions kernel modules ...done.
Doing non-kernel setup of the Guest Additions ...done.
You should restart your guest to make sure the new modules are actually used

Installing the Window System drivers
Could not find the X.Org or XFree86 Window System, skipping.
An error occurred during installation of VirtualBox Guest Additions 4.3.10. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
stdin: is not a tty
Cleaning up downloaded VirtualBox Guest Additions ISO...
[default] Setting hostname...
[default] Configuring and enabling network interfaces...
[default] Mounting shared folders...
[default] -- /vagrant
Failed to mount folders in Linux guest. This is usually beacuse
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` /vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` /vagrant /vagrant

**Comment by maoo** [comment]
Hi @marsbard , any update on this issue? Have you tried using latest Vagrant version? Thanks!

**Comment by marsbard** [comment]
To be honest I haven't tried it recently @maoo but for another project that was giving me the same difficulties I removed the vagrant-vbguest plugin.

**Comment by maoo** [comment]
Thank you for the feedback, added to the docs

**Comment by idwright** [comment]
Looks like it's a problem with the version of VirtualBox - 4.3.10 as used by Ubuntu 14.04

See this issue - https://github.com/mitchellh/vagrant/issues/3341

A fix is to add the following line to the end of scripts/vbox-additions.sh

test -d /opt/VBoxGuestAdditions-4.3.10/lib/VBoxGuestAdditions && ln -s /opt/VBoxGuestAdditions-4.3.10/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions
