### ISSUE TITLE
 default: Error executing action `put` on resource 'maven[mysqlconnector]'

### ISSUE THREAD

**Issue by hoecake** [maoo/alfresco-boxes#22]
Hello ,
Thanks for your works.

I set up  Alfresco Boxes on my Mac ,but it always has error as follow: 
Could you please give some help ? 
Thanks
Regards,
Henry

https://gist.github.com/maoo/0a77631a8833d080270e

**Comment by maoo** [comment]
Hi @hoecake , have you fixed your Maven settings? Is there anything else I can help with? Maybe we should add some documentation? Thanks.

**Comment by maoo** [comment]
dup of #29
