### ISSUE TITLE
Problem with version constraints in Berksfile

### ISSUE THREAD

**Issue by michaeldunstan** [maoo/alfresco-boxes#25]
I needed rewrite the version constraints in `Berksfile` so that `create-vendor-cookbooks.sh` would install the expected versions of the cookbooks. (Otherwise the vagrant provisioning would fail when processing the mysql cookbook.)

Here is what `berks list` reports before editing `Berksfile`:

    Cookbooks installed by your Berksfile:
      * 7-zip (1.0.2)
      * alfresco (0.4.1) from git://github.com/maoo/chef-alfresco.git (at chef-alfresco-0.4.2)
      * apache2 (3.0.0)
      * apt (2.6.1)
      * ark (0.9.0)
      * artifact-deployer (0.7.5) from git://github.com/maoo/artifact-deployer.git (at artifact-deployer-0.7.5)
      * build-essential (2.1.3)
      * chef-sugar (2.5.0)
      * chef_handler (1.1.6)
      * database (4.0.1)
      * file (2.0.0) from git://github.com/jenssegers/chef-file.git (at v1.0.0)
      * imagemagick (0.2.3)
      * iptables (0.14.1)
      * java (1.31.0)
      * logrotate (1.8.0)
      * maven (1.2.0)
      * mysql (6.0.13)
      * openoffice (0.2.4) from git://github.com/dhartford/chef-openoffice.git (at master)
      * openssl (2.0.2)
      * postgresql (3.4.14)
      * rbac (1.0.2)
      * resolver (1.2.0)
      * resource-control (0.1.1)
      * smf (2.2.1)
      * swftools (0.2.6) from git://github.com/dhartford/chef-swftools.git (at master)
      * tar (0.6.0)
      * tomcat (0.15.12) from git://github.com/maoo/tomcat.git (at chef-tomcat-0.15.12-custom-4)
      * windows (1.36.1)
      * yum (3.5.2)
      * yum-centos (0.3.0)
      * yum-epel (0.6.0)
      * yum-mysql-community (0.1.12)
      * yum-repoforge (0.5.0)

Then edit `Berksfile` to use version constraints such as `'= 5.5.4'` for the community(?) hosted cookbooks. (And add an entry for `mysql-chef_gem`.) The `Berksfile` then reads as:

    source "https://api.berkshelf.com"

    cookbook 'yum-centos',              '= 0.2.2'
    cookbook 'ark',                     '= 0.9.0'
    cookbook 'resolver',                '= 1.2.0'
    cookbook 'mysql',                   '= 5.5.4'
    cookbook 'mysql-chef_gem',          '= 0.0.5'
    cookbook 'database',                '= 2.3.0'
    cookbook 'java',                    '= 1.28.0'
    cookbook 'openssl',                 '= 2.0.0'
    cookbook 'maven',                   '= 1.2.0'
    cookbook 'iptables',                '= 0.14.0'
    cookbook 'imagemagick',             '= 0.2.3'

    cookbook 'file',                    git: 'git://github.com/jenssegers/chef-file.git', tag: 'v1.0.0'

    cookbook 'swftools',                git: 'git://github.com/dhartford/chef-swftools.git'
    cookbook 'openoffice',              git: 'git://github.com/dhartford/chef-openoffice.git'

    cookbook 'alfresco',                git: 'git://github.com/maoo/chef-alfresco.git',      tag: 'chef-alfresco-0.4.2'
    cookbook 'artifact-deployer',       git: 'git://github.com/maoo/artifact-deployer.git',  tag: 'artifact-deployer-0.7.5'
    cookbook 'tomcat',                  git: 'git://github.com/maoo/tomcat.git',             tag: 'chef-tomcat-0.15.12-custom-4'

And now `berks list` returns:

    Cookbooks installed by your Berksfile:
      * 7-zip (1.0.2)
      * alfresco (0.4.1) from git://github.com/maoo/chef-alfresco.git (at chef-alfresco-0.4.2)
      * apache2 (3.0.0)
      * apt (2.6.1)
      * ark (0.9.0)
      * artifact-deployer (0.7.5) from git://github.com/maoo/artifact-deployer.git (at artifact-deployer-0.7.5)
      * aws (2.5.0)
      * build-essential (2.1.3)
      * chef-sugar (2.5.0)
      * chef_handler (1.1.6)
      * database (2.3.0)
      * file (2.0.0) from git://github.com/jenssegers/chef-file.git (at v1.0.0)
      * imagemagick (0.2.3)
      * iptables (0.14.0)
      * java (1.28.0)
      * logrotate (1.8.0)
      * maven (1.2.0)
      * mysql (5.5.4)
      * mysql-chef_gem (0.0.5)
      * openoffice (0.2.4) from git://github.com/dhartford/chef-openoffice.git (at master)
      * openssl (2.0.0)
      * postgresql (3.4.14)
      * resolver (1.2.0)
      * swftools (0.2.6) from git://github.com/dhartford/chef-swftools.git (at master)
      * tar (0.6.0)
      * tomcat (0.15.12) from git://github.com/maoo/tomcat.git (at chef-tomcat-0.15.12-custom-4)
      * windows (1.36.1)
      * xfs (1.1.0)
      * yum (3.5.2)
      * yum-centos (0.2.2)
      * yum-epel (0.6.0)
      * yum-mysql-community (0.1.12)
      * yum-repoforge (0.5.0)

I'm using `berks` version 3.2.3.

**Comment by maoo** [comment]
Hi Michael, I don't understand what the issue is; are you able to use alfresco-boxes with your Berksfile change? If not, what exactly is the issue? Can you paste some result?

Make sure you always delete Berksfile.lock before running any `berks` command.

Out of curiosity, are you using Packer, Vagrant and/or Docker with Alfresco boxes?

Thanks.

**Comment by michaelsuzukisagi** [comment]
hi, i didnt raise the issue.
On 9 Feb 2015, at 11:49, Maurizio Pillitu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Michael, I don't understand what the issue is; are you able to use alfresco-boxes with your Berksfile change? If not, what exactly is the issue? Can you paste some result?

Make sure you always delete Berksfile.lock before running any berks command.

Out of curiosity, are you using Packer, Vagrant and/or Docker with Alfresco boxes?

Thanks.

**Comment by michaeldunstan** [comment]
Hi @maoo, oops - sorry I was not as clear as I could have been.

I was able to successfully use alfresco-boxes after editing `Berksfile`.

(Although I do run into another problem later on during the Vagrant provisioning where the download for alfresco-mmt fails. See #26.)

I've been running `create-vendor-cookbooks.sh` to process the `Berksfile` each time. Only using `berks list` to inspect the results. So `Berksfile.lock` and all the cookbooks should be removed each time the `Berksfile` is processed.

I'm using Vagrant with Alfresco boxes.

Here is how I can recreate the original problem:

    git clone https://github.com/maoo/alfresco-boxes.git
    cd alfresco-boxes/common
    sh create-vendor-cookbooks.sh
    cd ../vagrant
    vagrant up

The last command fails with a Recipe Compile Error: could not find recipe server for cookbook mysql:

    Using 'precise64' as source Vagrant box
    Using 'alfresco-allinone-dev.json' as JSON Chef configuration
    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Importing base box 'precise64'...
    ==> default: Matching MAC address for NAT networking...
    ==> default: Setting the name of the VM: vagrant_default_1423509893589_71534
    ==> default: Clearing any previously set network interfaces...
    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 1: nat
        default: Adapter 2: hostonly
    ==> default: Forwarding ports...
        default: 22 => 2222 (adapter 1)
    ==> default: Running 'pre-boot' VM customizations...
    ==> default: Booting VM...
    ==> default: Waiting for machine to boot. This may take a few minutes...
        default: SSH address: 127.0.0.1:2222
        default: SSH username: vagrant
        default: SSH auth method: private key
        default: Warning: Connection timeout. Retrying...
        default: 
        default: Vagrant insecure key detected. Vagrant will automatically replace
        default: this with a newly generated keypair for better security.
        default: 
        default: Inserting generated public key within guest...
        default: Removing insecure key from the guest if its present...
        default: Key inserted! Disconnecting and reconnecting using new SSH key...
    ==> default: Machine booted and ready!
    GuestAdditions versions on your host (4.3.20) and guest (4.2.0) do not match.
    stdin: is not a tty
    Reading package lists...
    Building dependency tree...
    Reading state information...
    The following extra packages will be installed:
      fakeroot linux-headers-3.2.0-23 make patch
    Suggested packages:
      make-doc diffutils-doc
    The following NEW packages will be installed:
      dkms fakeroot linux-headers-3.2.0-23 linux-headers-3.2.0-23-generic make
      patch
    0 upgraded, 6 newly installed, 0 to remove and 66 not upgraded.
    Need to get 12.7 MB of archives.
    After this operation, 68.5 MB of additional disk space will be used.
    Get:1 http://us.archive.ubuntu.com/ubuntu/ precise/main make amd64 3.81-8.1ubuntu1 [118 kB]
    Get:2 http://us.archive.ubuntu.com/ubuntu/ precise/main patch amd64 2.6.1-3 [80.2 kB]
    Get:3 http://us.archive.ubuntu.com/ubuntu/ precise/main dkms all 2.2.0.3-1ubuntu3 [73.1 kB]
    Get:4 http://us.archive.ubuntu.com/ubuntu/ precise/main fakeroot amd64 1.18.2-1 [87.2 kB]
    Get:5 http://us.archive.ubuntu.com/ubuntu/ precise/main linux-headers-3.2.0-23 all 3.2.0-23.36 [11.4 MB]
    Get:6 http://us.archive.ubuntu.com/ubuntu/ precise/main linux-headers-3.2.0-23-generic amd64 3.2.0-23.36 [947 kB]
    dpkg-preconfigure: unable to re-open stdin: No such file or directory
    Fetched 12.7 MB in 8s (1,427 kB/s)
    Selecting previously unselected package make.
    (Reading database ... 51095 files and directories currently installed.)
    Unpacking make (from .../make_3.81-8.1ubuntu1_amd64.deb) ...
    Selecting previously unselected package patch.
    Unpacking patch (from .../patch_2.6.1-3_amd64.deb) ...
    Selecting previously unselected package dkms.
    Unpacking dkms (from .../dkms_2.2.0.3-1ubuntu3_all.deb) ...
    Selecting previously unselected package fakeroot.
    Unpacking fakeroot (from .../fakeroot_1.18.2-1_amd64.deb) ...
    Selecting previously unselected package linux-headers-3.2.0-23.
    Unpacking linux-headers-3.2.0-23 (from .../linux-headers-3.2.0-23_3.2.0-23.36_all.deb) ...
    Selecting previously unselected package linux-headers-3.2.0-23-generic.
    Unpacking linux-headers-3.2.0-23-generic (from .../linux-headers-3.2.0-23-generic_3.2.0-23.36_amd64.deb) ...
    Processing triggers for man-db ...
    Setting up make (3.81-8.1ubuntu1) ...
    Setting up patch (2.6.1-3) ...
    Setting up dkms (2.2.0.3-1ubuntu3) ...
    Setting up fakeroot (1.18.2-1) ...
    update-alternatives: using /usr/bin/fakeroot-sysv to provide /usr/bin/fakeroot (fakeroot) in auto mode.
    Setting up linux-headers-3.2.0-23 (3.2.0-23.36) ...
    Setting up linux-headers-3.2.0-23-generic (3.2.0-23.36) ...
    Examining /etc/kernel/header_postinst.d.
    run-parts: executing /etc/kernel/header_postinst.d/dkms 3.2.0-23-generic /boot/vmlinuz-3.2.0-23-generic
    Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
    stdin: is not a tty
    mount: warning: /mnt seems to be mounted read-only.
    Installing Virtualbox Guest Additions 4.3.20 - guest version is 4.2.0
    stdin: is not a tty
    Verifying archive integrity... All good.
    Uncompressing VirtualBox 4.3.20 Guest Additions for Linux............
    VirtualBox Guest Additions installer
    Removing installed version 4.2.0 of VirtualBox Guest Additions...
    Copying additional installer modules ...
    Installing additional modules ...
    Removing existing VirtualBox DKMS kernel modules ...done.
    Removing existing VirtualBox non-DKMS kernel modules ...done.
    Building the VirtualBox Guest Additions kernel modules ...done.
    Doing non-kernel setup of the Guest Additions ...done.
    You should restart your guest to make sure the new modules are actually used

    Installing the Window System drivers
    Could not find the X.Org or XFree86 Window System, skipping.
    An error occurred during installation of VirtualBox Guest Additions 4.3.20. Some functionality may not work as intended.
    In most cases it is OK that the "Window System drivers" installation failed.
    stdin: is not a tty
    ==> default: Checking for guest additions in VM...
    ==> default: Setting hostname...
    ==> default: Configuring and enabling network interfaces...
    ==> default: Mounting shared folders...
        default: /vagrant => /opt/sites/androgogic/alfresco-boxes-issues/alfresco-boxes/vagrant
        default: /tmp/vagrant-chef-solo/bc7fc72825049be1e58a74240c696c92/cookbooks => /opt/sites/androgogic/alfresco-boxes-issues/alfresco-boxes/common/vendor-cookbooks
        default: /tmp/vagrant-chef-solo/0ba1e9f1e55b443d3d699f7663067eee/data_bags => /opt/sites/androgogic/alfresco-boxes-issues/alfresco-boxes/common/data_bags
    ==> default: Installing Chef 11.16.2 Omnibus package...
    ==> default: Downloading Chef 11.16.2 for ubuntu...
    ==> default: downloading https://www.chef.io/chef/metadata?v=11.16.2&prerelease=false&nightlies=false&p=ubuntu&pv=12.04&m=x86_64
    ==> default:   to file /tmp/install.sh.4409/metadata.txt
    ==> default: trying wget...
    ==> default: url	https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef_11.16.2-1_amd64.deb
    ==> default: md5	a2b20f34bc7d7dc0a6e0636caa314c03
    ==> default: sha256	dd3360ea2fd238f3bec962bdb3bb179060701bc67ac5cad3eed4be1b1c1afe8f
    ==> default: downloaded metadata file looks valid...
    ==> default: downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef_11.16.2-1_amd64.deb
    ==> default:   to file /tmp/install.sh.4409/chef_11.16.2-1_amd64.deb
    ==> default: trying wget...
    ==> default: Comparing checksum with sha256sum...
    ==> default: Installing Chef 11.16.2
    ==> default: installing with dpkg...
    ==> default: Selecting previously unselected package chef.
    ==> default: (Reading database ... 
    ==> default: 73195 files and directories currently installed.)
    ==> default: Unpacking chef (from .../chef_11.16.2-1_amd64.deb) ...
    ==> default: Setting up chef (11.16.2-1) ...
    ==> default: Thank you for installing Chef!
    ==> default: Running provisioner: chef_solo...
    ==> default: Detected Chef (latest) is already installed
    Generating chef JSON and uploading...
    ==> default: Running chef-solo...
    ==> default: stdin: is not a tty
    ==> default: [2015-02-09T19:26:55+00:00] INFO: Forking chef instance to converge...
    ==> default: [2015-02-09T19:26:55+00:00] WARN: 
    ==> default: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    ==> default: SSL validation of HTTPS requests is disabled. HTTPS connections are still
    ==> default: encrypted, but chef is not able to detect forged replies or man in the middle
    ==> default: attacks.
    ==> default: 
    ==> default: To fix this issue add an entry like this to your configuration file:
    ==> default: 
    ==> default: ```
    ==> default:   # Verify all HTTPS connections (recommended)
    ==> default:   ssl_verify_mode :verify_peer
    ==> default: 
    ==> default:   # OR, Verify only connections to chef-server
    ==> default:   verify_api_cert true
    ==> default: ```
    ==> default: 
    ==> default: To check your SSL configuration, or troubleshoot errors, you can use the
    ==> default: `knife ssl check` command like so:
    ==> default: 
    ==> default: ```
    ==> default:   knife ssl check -c /tmp/vagrant-chef-solo/solo.rb
    ==> default: ```
    ==> default: 
    ==> default: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    ==> default: [2015-02-09T19:26:55+00:00] INFO: *** Chef 11.16.2 ***
    ==> default: [2015-02-09T19:26:55+00:00] INFO: Chef-client pid: 4582
    ==> default: [2015-02-09T19:26:57+00:00] INFO: Setting the run_list to ["recipe[apt::default]", "recipe[alfresco::default]"] from CLI options
    ==> default: [2015-02-09T19:26:57+00:00] INFO: Run List is [recipe[apt::default], recipe[alfresco::default]]
    ==> default: [2015-02-09T19:26:57+00:00] INFO: Run List expands to [apt::default, alfresco::default]
    ==> default: [2015-02-09T19:26:57+00:00] INFO: Starting Chef Run for alfresco-allinone
    ==> default: [2015-02-09T19:26:57+00:00] INFO: Running start handlers
    ==> default: [2015-02-09T19:26:57+00:00] INFO: Start handlers complete.
    ==> default: 
    ==> default: ================================================================================
    ==> default: Recipe Compile Error
    ==> default: ================================================================================
    ==> default: 
    ==> default: Chef::Exceptions::RecipeNotFound
    ==> default: --------------------------------
    ==> default: could not find recipe server for cookbook mysql
    ==> default: 
    ==> default: 
    ==> default: [2015-02-09T19:26:59+00:00] ERROR: Running exception handlers
    ==> default: [2015-02-09T19:26:59+00:00] ERROR: Exception handlers complete
    ==> default: [2015-02-09T19:26:59+00:00] FATAL: Stacktrace dumped to /tmp/vagrant-chef-solo/chef-stacktrace.out
    ==> default: [2015-02-09T19:26:59+00:00] ERROR: could not find recipe server for cookbook mysql
    ==> default: [2015-02-09T19:26:59+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
    Chef never successfully completed! Any errors should be visible in the
    output above. Please fix your recipes so that they properly complete.

And I reckon that error is because the wrong version of the mysql cookbook (version 6.0.13) has been installed by berks.

The error can be avoided by starting all over and editing the `Berksfile` just before running `create-vendor-cookbooks.sh`. The edit is to replace version specifiers for the community cookbooks like:

    tag: 'v5.5.4'

with:

    '= 5.5.4'

See the original comment for the full `Berksfile` I use.

Cheers

**Comment by maoo** [comment]
Hi Michael, thanks for the notification; yes, the syntax you mention is much cleaner and I will refactor all Berksfile, pointing to this issue.

Next time, feel free to submit a Pull Request with your file definition.

Thanks!

**Comment by michaeldunstan** [comment]
Thanks for the update. Looks like there are two problems going on:

- The syntax for pinning versions. Which is covered by your commit above.
- Some cookbooks are not detail in `Berksfile` and are open to potential version conflicts. I've created pull request #27 to cover that.
