### ISSUE TITLE
Missing download for alfresco-mmt

### ISSUE THREAD

**Issue by michaeldunstan** [maoo/alfresco-boxes#26]
I'm using Vagrant with Alfresco boxes. Processing artifact `alfresco-mmt.jar` fails find a suitable download. Here is the error reported when running `vagrant up`:

    ==> default: [2015-02-09T21:05:15+00:00] INFO: Processing artifact alfresco-mmt.jar; unzip: false
    ==> default: 
    ==> default: ================================================================================
    ==> default: Error executing action `put` on resource 'maven[alfresco-mmt]'
    ==> default: ================================================================================
    ==> default: 
    ==> default: 
    ==> default: Mixlib::ShellOut::ShellCommandFailed
    ==> default: ------------------------------------
    ==> default: Expected process to exit with [0], but received '1'
    ==> default: 
    ==> default: ---- Begin output of mvn org.apache.maven.plugins:maven-dependency-plugin:2.4:get -DgroupId=it.session.alfresco -DartifactId=alfresco-mmt -Dversion=4.2.1.4 -Dpackaging=jar -Dclassifier=fatjar -Ddest=/tmp/chef_maven_lwrp20150209-4646-1kshobc/alfresco-mmt.jar -DremoteRepositories=maoo-public::::https://repository-maoo.forge.cloudbees.com/release,public::::https://artifacts.alfresco.com/nexus/content/groups/public -Dtransitive=false ----
    ==> default: 
    ==> default: STDOUT: [INFO] Scanning for projects...
    ==> default: 
    ==> default: [INFO]                                                                         
    ==> default: [INFO] ------------------------------------------------------------------------
    ==> default: 
    ==> default: [INFO] Building Maven Stub Project (No POM) 1
    ==> default: [INFO] ------------------------------------------------------------------------
    ==> default: [INFO] 
    ==> default: [INFO] --- maven-dependency-plugin:2.4:get (default-cli) @ standalone-pom ---
    ==> default: 
    ==> default: Downloading: http://repo.maven.apache.org/maven2/it/session/alfresco/alfresco-mmt/4.2.1.4/alfresco-mmt-4.2.1.4-fatjar.jar
    ==> default: 
    Downloading: https://repository-maoo.forge.cloudbees.com/release/it/session/alfresco/alfresco-mmt/4.2.1.4/alfresco-mmt-4.2.1.4-fatjar.jar
    ==> default: 
    Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/it/session/alfresco/alfresco-mmt/4.2.1.4/alfresco-mmt-4.2.1.4-fatjar.jar
    ==> default: 
    [INFO] ------------------------------------------------------------------------
    ==> default: [INFO] BUILD FAILURE
    ==> default: [INFO] ------------------------------------------------------------------------
    ==> default: [INFO] Total time: 6.110s
    ==> default: [INFO] Finished at: Mon Feb 09 21:05:22 UTC 2015
    ==> default: 
    ==> default: [INFO] Final Memory: 15M/107M
    ==> default: [INFO] ------------------------------------------------------------------------
    ==> default: 
    ==> default: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.4:get (default-cli) on project standalone-pom: Couldn't download artifact: Could not find artifact it.session.alfresco:alfresco-mmt:jar:fatjar:4.2.1.4 in central (http://repo.maven.apache.org/maven2)
    ==> default: 
    ==> default: [ERROR] 
    ==> default: [ERROR] Try downloading the file manually from the project website.
    ==> default: [ERROR] 
    ==> default: [ERROR] Then, install it using the command:
    ==> default: [ERROR] mvn install:install-file -DgroupId=it.session.alfresco -DartifactId=alfresco-mmt -Dversion=4.2.1.4 -Dclassifier=fatjar -Dpackaging=jar -Dfile=/path/to/file
    ==> default: [ERROR] 
    ==> default: [ERROR] Alternatively, if you host your own repository you can deploy the file there:
    ==> default: [ERROR] mvn deploy:deploy-file -DgroupId=it.session.alfresco -DartifactId=alfresco-mmt -Dversion=4.2.1.4 -Dclassifier=fatjar -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
    ==> default: 
    ==> default: [ERROR] 
    ==> default: [ERROR] 
    ==> default: [ERROR] it.session.alfresco:alfresco-mmt:jar:4.2.1.4
    ==> default: [ERROR] 
    ==> default: [ERROR] from the specified remote repositories:
    ==> default: [ERROR] central (http://repo.maven.apache.org/maven2, releases=true, snapshots=false),
    ==> default: [ERROR] maoo-public (https://repository-maoo.forge.cloudbees.com/release, releases=true, snapshots=true),
    ==> default: [ERROR] public (https://artifacts.alfresco.com/nexus/content/groups/public, releases=true, snapshots=true)
    ==> default: [ERROR] -> [Help 1]
    ==> default: [ERROR] 
    ==> default: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    ==> default: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    ==> default: [ERROR] 
    ==> default: [ERROR] For more information about the errors and possible solutions, please read the following articles:
    ==> default: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
    ==> default: 
    ==> default: STDERR: 
    ==> default: ---- End output of mvn org.apache.maven.plugins:maven-dependency-plugin:2.4:get -DgroupId=it.session.alfresco -DartifactId=alfresco-mmt -Dversion=4.2.1.4 -Dpackaging=jar -Dclassifier=fatjar -Ddest=/tmp/chef_maven_lwrp20150209-4646-1kshobc/alfresco-mmt.jar -DremoteRepositories=maoo-public::::https://repository-maoo.forge.cloudbees.com/release,public::::https://artifacts.alfresco.com/nexus/content/groups/public -Dtransitive=false ----
    ==> default: Ran mvn org.apache.maven.plugins:maven-dependency-plugin:2.4:get -DgroupId=it.session.alfresco -DartifactId=alfresco-mmt -Dversion=4.2.1.4 -Dpackaging=jar -Dclassifier=fatjar -Ddest=/tmp/chef_maven_lwrp20150209-4646-1kshobc/alfresco-mmt.jar -DremoteRepositories=maoo-public::::https://repository-maoo.forge.cloudbees.com/release,public::::https://artifacts.alfresco.com/nexus/content/groups/public -Dtransitive=false returned 1
    ==> default: 
    ==> default: Cookbook Trace:
    ==> default: ---------------
    ==> default: /tmp/vagrant-chef-solo/bc7fc72825049be1e58a74240c696c92/cookbooks/maven/providers/default.rb:55:in `block in get_mvn_artifact'
    ==> default: /tmp/vagrant-chef-solo/bc7fc72825049be1e58a74240c696c92/cookbooks/maven/providers/default.rb:53:in `get_mvn_artifact'
    ==> default: 
    ==> default: /tmp/vagrant-chef-solo/bc7fc72825049be1e58a74240c696c92/cookbooks/maven/providers/default.rb:85:in `block (2 levels) in class_from_file'
    ==> default: /tmp/vagrant-chef-solo/bc7fc72825049be1e58a74240c696c92/cookbooks/maven/providers/default.rb:84:in `block in class_from_file'
    ==> default: 
    ==> default: Resource Declaration:
    ==> default: ---------------------
    ==> default: # In /tmp/vagrant-chef-solo/bc7fc72825049be1e58a74240c696c92/cookbooks/artifact-deployer/recipes/artifacts.rb
    ==> default: 
    ==> default:  55:       maven "#{artifactName}" do
    ==> default:  56:         artifact_id   artifact_id
    ==> default:  57:         group_id      group_id
    ==> default:  58:         version       version
    ==> default:  59:         if classifier != ''
    ==> default:  60:           classifier  classifier
    ==> default:  61:         end
    ==> default:  62:         action        :put
    ==> default: 
    ==> default: 
    ==> default: Compiled Resource:
    ==> default: ------------------
    ==> default: # Declared in /tmp/vagrant-chef-solo/bc7fc72825049be1e58a74240c696c92/cookbooks/artifact-deployer/recipes/artifacts.rb:55:in `block in from_file'
    ==> default: 
    ==> default: maven("alfresco-mmt") do
    ==> default:   action [:put]
    ==> default:   retries 0
    ==> default:   retry_delay 2
    ==> default:   guard_interpreter :default
    ==> default:   artifact_id "alfresco-mmt"
    ==> default: 
    ==> default:   repositories ["maoo-public::::https://repository-maoo.forge.cloudbees.com/release", "public::::https://artifacts.alfresco.com/nexus/content/groups/public"]
    ==> default:   cookbook_name :"artifact-deployer"
    ==> default:   recipe_name "artifacts"
    ==> default:   group_id "it.session.alfresco"
    ==> default:   version "4.2.1.4"
    ==> default:   dest "/var/chef/cache"
    ==> default:   owner "tomcat7"
    ==> default:   packaging "jar"
    ==> default:   classifier "fatjar"
    ==> default: end
    ==> default: 
    ==> default: 
    ==> default: 
    ==> default: [2015-02-09T21:05:22+00:00] INFO: Running queued delayed notifications before re-raising exception
    ==> default: [2015-02-09T21:05:22+00:00] INFO: template[/etc/default/tomcat7] sending nothing action to service[tomcat] (delayed)
    ==> default: [2015-02-09T21:05:22+00:00] ERROR: Running exception handlers
    ==> default: [2015-02-09T21:05:22+00:00] ERROR: Exception handlers complete
    ==> default: [2015-02-09T21:05:22+00:00] FATAL: Stacktrace dumped to /tmp/vagrant-chef-solo/chef-stacktrace.out
    ==> default: [2015-02-09T21:05:22+00:00] ERROR: maven[alfresco-mmt] (artifact-deployer::artifacts line 55) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ==> default: ---- Begin output of mvn org.apache.maven.plugins:maven-dependency-plugin:2.4:get -DgroupId=it.session.alfresco -DartifactId=alfresco-mmt -Dversion=4.2.1.4 -Dpackaging=jar -Dclassifier=fatjar -Ddest=/tmp/chef_maven_lwrp20150209-4646-1kshobc/alfresco-mmt.jar -DremoteRepositories=maoo-public::::https://repository-maoo.forge.cloudbees.com/release,public::::https://artifacts.alfresco.com/nexus/content/groups/public -Dtransitive=false ----
    ==> default: STDOUT: [INFO] Scanning for projects...
    ==> default: [INFO]                                                                         
    ==> default: [INFO] ------------------------------------------------------------------------
    ==> default: [INFO] Building Maven Stub Project (No POM) 1
    ==> default: [INFO] ------------------------------------------------------------------------
    ==> default: [INFO] 
    ==> default: [INFO] --- maven-dependency-plugin:2.4:get (default-cli) @ standalone-pom ---
    ==> default: Downloading: http://repo.maven.apache.org/maven2/it/session/alfresco/alfresco-mmt/4.2.1.4/alfresco-mmt-4.2.1.4-fatjar.jar
    Downloading: https://repository-maoo.forge.cloudbees.com/release/it/session/alfresco/alfresco-mmt/4.2.1.4/alfresco-mmt-4.2.1.4-fatjar.jar
    Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/it/session/alfresco/alfresco-mmt/4.2.1.4/alfresco-mmt-4.2.1.4-fatjar.jar
    [INFO] ------------------------------------------------------------------------
    ==> default: [INFO] BUILD FAILURE
    ==> default: [INFO] ------------------------------------------------------------------------
    ==> default: [INFO] Total time: 6.110s
    ==> default: [INFO] Finished at: Mon Feb 09 21:05:22 UTC 2015
    ==> default: [INFO] Final Memory: 15M/107M
    ==> default: [INFO] ------------------------------------------------------------------------
    ==> default: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.4:get (default-cli) on project standalone-pom: Couldn't download artifact: Could not find artifact it.session.alfresco:alfresco-mmt:jar:fatjar:4.2.1.4 in central (http://repo.maven.apache.org/maven2)
    ==> default: [ERROR] 
    ==> default: [ERROR] Try downloading the file manually from the project website.
    ==> default: [ERROR] 
    ==> default: [ERROR] Then, install it using the command:
    ==> default: [ERROR] mvn install:install-file -DgroupId=it.session.alfresco -DartifactId=alfresco-mmt -Dversion=4.2.1.4 -Dclassifier=fatjar -Dpackaging=jar -Dfile=/path/to/file
    ==> default: [ERROR] 
    ==> default: [ERROR] Alternatively, if you host your own repository you can deploy the file there:
    ==> default: [ERROR] mvn deploy:deploy-file -DgroupId=it.session.alfresco -DartifactId=alfresco-mmt -Dversion=4.2.1.4 -Dclassifier=fatjar -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
    ==> default: [ERROR] 
    ==> default: [ERROR] 
    ==> default: [ERROR] it.session.alfresco:alfresco-mmt:jar:4.2.1.4
    ==> default: [ERROR] 
    ==> default: [ERROR] from the specified remote repositories:
    ==> default: [ERROR] central (http://repo.maven.apache.org/maven2, releases=true, snapshots=false),
    ==> default: [ERROR] maoo-public (https://repository-maoo.forge.cloudbees.com/release, releases=true, snapshots=true),
    ==> default: [ERROR] public (https://artifacts.alfresco.com/nexus/content/groups/public, releases=true, snapshots=true)
    ==> default: [ERROR] -> [Help 1]
    ==> default: [ERROR] 
    ==> default: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    ==> default: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    ==> default: [ERROR] 
    ==> default: [ERROR] For more information about the errors and possible solutions, please read the following articles:
    ==> default: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
    ==> default: STDERR: 
    ==> default: ---- End output of mvn org.apache.maven.plugins:maven-dependency-plugin:2.4:get -DgroupId=it.session.alfresco -DartifactId=alfresco-mmt -Dversion=4.2.1.4 -Dpackaging=jar -Dclassifier=fatjar -Ddest=/tmp/chef_maven_lwrp20150209-4646-1kshobc/alfresco-mmt.jar -DremoteRepositories=maoo-public::::https://repository-maoo.forge.cloudbees.com/release,public::::https://artifacts.alfresco.com/nexus/content/groups/public -Dtransitive=false ----
    ==> default: Ran mvn org.apache.maven.plugins:maven-dependency-plugin:2.4:get -DgroupId=it.session.alfresco -DartifactId=alfresco-mmt -Dversion=4.2.1.4 -Dpackaging=jar -Dclassifier=fatjar -Ddest=/tmp/chef_maven_lwrp20150209-4646-1kshobc/alfresco-mmt.jar -DremoteRepositories=maoo-public::::https://repository-maoo.forge.cloudbees.com/release,public::::https://artifacts.alfresco.com/nexus/content/groups/public -Dtransitive=false returned 1
    ==> default: [2015-02-09T21:05:22+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
    Chef never successfully completed! Any errors should be visible in the
    output above. Please fix your recipes so that they properly complete.

I've tried downloading all three URL's for alfresco-mmt-4.2.1.4-fatjar.jar reported in the error log. They all return a 404.

Vagrant provisioning is successful if I comment out all 8 lines for `alfresco-mmt` in `common/vendor-cookbooks/alfresco/attributes/repo_config.rb` before running `vagrant up`. After successful provisioning Alfresco is up and running in the Vagrant VM. But of course the VM is missing an install of alfresco-mmt and running `apply_amps.sh` will fail.

**Comment by maoo** [comment]
I confirm the issue, working on the solution

**Comment by maoo** [comment]
The problem is caused by a wrong mmt file used (I used to use my own one, since Alfresco wasn't shipping a fatjar for 4.2 version).

You should be able to override these values (without re-launching Berkshelf) from your Packer/Vagrant definitions:

```
"artifacts" {
  "alfresco-mmt" : {
    "groupId" : "org.alfresco",
    "artifactId" : "alfresco-mmt",
    "version" : "5.0.c"
  }
}
```

Please let me know if this works for you.

**Comment by michaeldunstan** [comment]
Thanks for that.

I tested without re-launching Berkshelf as you suggested.  I also need to add `"classifier": "",` to my overrides so that the correct URL is used to download the jar file. Nice to see the overrides in action there.

Also tested using a clean build of all the cookbooks.

In both cases alfresco-mmt is installed and apply_amps runs without error.

**Comment by maoo** [comment]
Nice! I'm glad you got it working. In the next months we're gonna work hard to consolidate Chef logic. Please open more issues if you have any problem with alfresco-boxes.

Thanks a lot for sharing!

**Comment by michaeldunstan** [comment]
Oh yeah - just to be very clear - the second test with the clean cookbooks was when I updated my local Berksfile to include your changes to chef-alfresco. By replacing:

    tag: 'chef-alfresco-0.4.2'

with:

    ref: '0e71911b4c7571f15c326c1f559e03b7ead999d9'
