### ISSUE TITLE
Long download results in "Command timed out after 600s"

### ISSUE THREAD

**Issue by michaeldunstan** [maoo/alfresco-boxes#28]
I often get a timeout error when maven is downloading content. Here is a typical example - https://gist.github.com/maoo/2f06215da972f8daa069

To get around that I manually increase the timeout by adding `:timeout => 6000` to the call to `shell_out()` in:

    common/vendor-cookbooks/maven/providers/default.rb

Is there some other way that the timeout can be increased without editing the cookbook? Or should the maven cookbook be updated to so that the timeout is a parameter that can be easily overridden? Or can the output from running maven be used as a heartbeat to avoid triggering the timeout during a long download?

**Comment by maoo** [comment]
I don't see any way we can override a Chef provider, but you could definitely submit a Pull Request (PR), making the timeout configurable, passing the (optional) configuration via maven LWRP; I think it would be really useful.

At that point we can decide to raise the default timeout in artifact-deployer, or make it configurable there too (to accommodate runs for those with a slower Internet connection)

Please let me know if you need some help on the PR.
Thanks!

**Comment by maoo** [comment]
Hi @michaeldunstan , I've branched out the maven cookbook, applying the change you suggested

https://github.com/maoo/maven/compare/opscode-cookbooks:master...master

I also updated artifact-deployer (master) to pass through the timeout configuration

https://github.com/maoo/artifact-deployer/commit/00ed302334e6f816d3751c6ebd96d8b34270cbcf

I'll try to find some time to test these changes in the next days; any feedback is more than welcome of course.

Thanks!

**Comment by maoo** [comment]
You are able now to define a `timeout` option in your `artifacts` item (check https://travis-ci.org/maoo/artifact-deployer/builds for history); please change your `Berksfile` to use `artifact-deployer` with `tag: 'master'`, add timeouts into your artifact definitions and let me know if it solves your issue.

**Comment by maoo** [comment]
FYI - https://github.com/opscode-cookbooks/maven/pull/53

**Comment by michaeldunstan** [comment]
Thanks @maoo. I updated my Berksfile to use:

    cookbook 'maven',                   git: 'git://github.com/maoo/maven.git',  tag: 'master'
    cookbook 'artifact-deployer',       git: 'git://github.com/maoo/artifact-deployer.git',  tag: 'master'

And added the following to `alfresco-allinone-dev.json`:

        "artifacts": {
          "alfresco": {
              "timeout": 6000
          }
        },

And that worked. `vagrant up` completed without error.

Looks the `alfresco` artifact just happens to be the only artifact big enough to run into the timeout problem for me.

Is there a way to specify a timeout for all the artifacts without setting each one individually? Like a wild card of the form: `"artifacts": {"*": {"timeout": 6000}}`?

**Comment by maoo** [comment]
You can now specify

```
"maven" : {
  "timeout": 60000
}
```

If you have any further issue, could you please open issue on https://github.com/maoo/artifact-deployer project?

Thank you very much for your feedback and collaboration!

**Comment by michaeldunstan** [comment]
Thanks @maoo. I tested that using:

    "artifacts": {
        "artifact-deployer": {
            "maven": {
                "timeout": 6000
            }
        }
    }
