### ISSUE TITLE
Unable to satisfy constraints on package artifact-deployer due to solution constraint (artifact-deployer = 0.8.6)

### ISSUE THREAD

**Issue by olimination** [maoo/alfresco-boxes#35]
With the current master I face following issue if I execute ./create-vendor-cookbooks.sh in "common" folder:
```
Resolving cookbook dependencies...
Fetching 'alfresco' from git://github.com/maoo/chef-alfresco.git (at master)
Fetching 'artifact-deployer' from git://github.com/maoo/artifact-deployer.git (at v0.8.6)
Fetching 'file' from git://github.com/jenssegers/chef-file.git (at v1.0.0)
Fetching 'maven' from git://github.com/maoo/maven.git (at master)
Fetching 'openoffice' from git://github.com/dhartford/chef-openoffice.git (at master)
Fetching 'swftools' from git://github.com/dhartford/chef-swftools.git (at master)
Fetching 'tomcat' from git://github.com/maoo/tomcat.git (at master)
Fetching cookbook index from https://api.berkshelf.com...
Unable to satisfy constraints on package artifact-deployer due to solution constraint (artifact-deployer = 0.8.6). Solution constraints that may result in a constraint on artifact-deployer: [(alfresco = 0.5.0) -> (artifact-deployer ~> 0.8.7)], [(artifact-deployer = 0.8.6)]
Demand that cannot be met: (artifact-deployer = 0.8.6)
Artifacts for which there are conflicting dependencies: artifact-deployer = 0.8.6 -> [(maven >= 0.0.0), (file >= 0.0.0), (python >= 0.0.0)]Unable to find a solution for demands: 7-zip (= 1.0.2), alfresco (0.5.0), apache2 (= 3.0.1), apt (= 2.6.1), ark (= 0.9.0), artifact-deployer (0.8.6), aws (= 2.6.0), build-essential (= 2.1.3), chef-sugar (= 2.5.0), chef_handler (= 1.1.6), database (= 2.3.0), file (2.0.0), imagemagick (= 0.2.3), iptables (= 0.14.0), java (= 1.28.0), logrotate (= 1.8.0), maven (1.2.0), mysql (= 5.5.4), mysql-chef_gem (= 0.0.5), openoffice (0.2.4), openssl (= 2.0.0), postgresql (= 3.4.14), resolver (= 1.2.0), swftools (0.2.6), tar (= 0.6.0), tomcat (0.17.3), windows (= 1.36.1), xfs (= 1.1.0), yum (= 3.5.2), yum-centos (= 0.2.2), yum-epel (= 0.6.0), yum-mysql-community (= 0.1.12), yum-repoforge (= 0.5.0)
```
Do I need to update any dependency?

Thanks for help.

**Comment by maoo** [comment]
Hi @olimination,
this is pretty weird; I did release artifact-deployer-0.8.7, but I don't understand why this should affect previous releases; I'll try to reproduce your issue and investigate further.

In the meantime, you could try updating to artifact-deployer-0.8.7 ; I'm currently using this version (along with chef-alfresco) and works fine for me (my Berksfile looks exactly the same).

Make sure you delete Berksfile.lock before any attempt, as this will force Berkshelf to update pointers to master branches used (unfortunately tomcat and maven projects are not released yet, I'm waiting for my Pull Requests to get approved).

Hope this helps, thanks for the issue!

mao

**Comment by olimination** [comment]
Thanks for your first response.

If I change following line in my common/Berksfile to:
```
cookbook 'artifact-deployer',       git: 'git://github.com/maoo/artifact-deployer.git',  tag: 'v0.8.7'
```
I get this error message:
```
Unable to satisfy constraints on package build-essential due to solution constraint (build-essential = 2.1.3). Solution constraints that may result in a constraint on build-essential: [(alfresco = 0.5.0) -> (artifact-deployer = 0.8.7) -> (python = {1.0.2,1.0.8,1.4.6}) -> (build-essential >= 0.0.0)], [(alfresco = 0.5.0) -> (build-essential ~> 2.2.3)], [(alfresco = 0.5.0) -> (database = 4.0.5) -> (postgresql = {3.4.6,2.4.0,3.4.18}) -> (build-essential >= 0.0.0)].....
....Demand that cannot be met: (build-essential = 2.1.3)
Artifacts for which there are conflicting dependencies: build-essential = 2.1.0 -> []Unable to find a solution for demands: 7-zip (= 1.0.2), alfresco (0.5.0), apache2 (= 3.0.1), apt (= 2.6.1), ark (= 0.9.0), artifact-deployer (0.8.7), aws (= 2.6.0), build-essential (= 2.1.3), chef-sugar (= 2.5.0), chef_handler (= 1.1.6), database (= 2.3.0), file (2.0.0), imagemagick (= 0.2.3), iptables (= 0.14.0), java (= 1.28.0), logrotate (= 1.8.0), maven (1.2.0), mysql (= 5.5.4)....
```
 I checked in the alfresco-boxes/common folder that I didn't have a Berksfile.lock. I use Berks version 3.2.3.

**Comment by michaeldunstan** [comment]
The original reported constraints problem is because the Berksfile specifies artefact-deployer as (see [alfresco-boxes/common/Berksfile](https://github.com/maoo/alfresco-boxes/blob/e55fed9737867bb3a13a7b7267000a6f68bf2e48/common/Berksfile#L37)):

    cookbook 'artifact-deployer',       git: 'git://github.com/maoo/artifact-deployer.git',  tag: 'v0.8.6'

Meanwhile the same Berksfile is pointing to the latest version of the alfresco cookbook which specifies artifact-deployer as (see [chef-alfresco/metadata.rb](https://github.com/maoo/chef-alfresco/blob/08b0025079621b70a906fa1981d998663b578775/metadata.rb#L15)):

    depends "artifact-deployer", "~> 0.8.7"

**Comment by maoo** [comment]
I was able to test it; I confirm what @michaeldunstan stated; I also realised that Berksfile contains a lot of entries that are not needed, since they are resolved as transitive dependencies of chef-alfresco.

Pushing shortly a polished version of Berksfile

**Comment by maoo** [comment]
Pushed - https://github.com/maoo/alfresco-boxes/commit/7c71fe8ad36ab333ada4ff2bb888b824dce9b55e . Please close issue if Berkshelf works for you too. TY!

**Comment by olimination** [comment]
worked perfectly! Thanks for the support.
